# Generated by Django 2.1.2 on 2018-11-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='q',
            new_name='qty',
        ),
    ]
