# Generated by Django 2.1.2 on 2018-11-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20181110_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ref_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
