# Generated by Django 2.1.3 on 2018-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20181112_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.OrderItem'),
        ),
    ]
