# Generated by Django 2.1.2 on 2018-10-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer_profile',
        ),
    ]
