# Generated by Django 2.1.3 on 2018-11-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181118_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='prod',
        ),
    ]
