# Generated by Django 2.1.3 on 2018-11-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_remove_vendorprofile_address'),
        ('customer', '0003_remove_customerprofile_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='prod',
            field=models.ManyToManyField(blank=True, to='vendor.Product'),
        ),
    ]
