# Generated by Django 2.1.2 on 2018-11-06 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0019_auto_20181104_2349'),
        ('customer', '0006_auto_20181104_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='prod',
            field=models.ManyToManyField(blank=True, to='vendor.Product'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cus', to=settings.AUTH_USER_MODEL),
        ),
    ]
