# Generated by Django 2.1.2 on 2018-11-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20181106_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='prod',
            field=models.ManyToManyField(null=True, to='vendor.Product'),
        ),
    ]
