# Generated by Django 2.1.2 on 2018-11-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20181106_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='prod',
            field=models.ManyToManyField(blank=True, to='vendor.Product'),
        ),
    ]
